// src/lib/dummy-data/MembersData.ts

export type Member = {
  id: number;
  name: string;
  nomorAnggota: string;
  jurusan?: string;
  nomorTelepon?: string;
  status: "Aktif" | "Alumni" | "Non-aktif";
  avatarUrl?: string;
};

export const MembersData: Member[] = [
  {
    id: 1,
    name: "Abdi Rahim",
    nomorAnggota: "001/KPA EMC²/1986",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 2,
    name: "John Mainer",
    nomorAnggota: "002/KPA EMC²/1986",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 3,
    name: "Edi P.J",
    nomorAnggota: "003/KPA EMC²/1986",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 4,
    name: "Replis",
    nomorAnggota: "004/KPA EMC²/1987",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 5,
    name: "Abdul Hamid",
    nomorAnggota: "005/KPA EMC²/1987",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 6,
    name: "Reza Pahlefi",
    nomorAnggota: "006/KPA EMC²/1988",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 7,
    name: "Murdiman",
    nomorAnggota: "007/KPA EMC²/1988",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 8,
    name: "Edwin Syarif",
    nomorAnggota: "008/KPA EMC²/1988",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 9,
    name: "Aprizal",
    nomorAnggota: "009/KPA EMC²/1988",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 10,
    name: "Saiful Bahri",
    nomorAnggota: "010/KPA EMC²/1988",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 11,
    name: "Hotland",
    nomorAnggota: "011/KPA EMC²/1988",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 12,
    name: "Chandra P.P",
    nomorAnggota: "012/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 13,
    name: "Trie Trisnawati",
    nomorAnggota: "013/KPA EMC²/1989",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 14,
    name: "Yuniati",
    nomorAnggota: "014/KPA EMC²/1989",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 15,
    name: "Purwanti",
    nomorAnggota: "015/KPA EMC²/1990",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 16,
    name: "Deskon Geofany",
    nomorAnggota: "016/KPA EMC²/1990",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 17,
    name: "Edi Haryanto",
    nomorAnggota: "017/KPA EMC²/1990",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 18,
    name: "Yuledi",
    nomorAnggota: "018/KPA EMC²/1990",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 19,
    name: "Rifa'i",
    nomorAnggota: "019/KPA EMC²/1990",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 20,
    name: "Khairil Anwar",
    nomorAnggota: "020/KPA EMC²/1990",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 21,
    name: "Hernelly",
    nomorAnggota: "021/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 22,
    name: "Zahrani",
    nomorAnggota: "022/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 23,
    name: "Farida Hanum",
    nomorAnggota: "023/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 24,
    name: "Asep",
    nomorAnggota: "024/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 25,
    name: "Sri Gustini",
    nomorAnggota: "025/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 26,
    name: "Heppy Lisnasari",
    nomorAnggota: "026/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 27,
    name: "Lisman Joni",
    nomorAnggota: "027/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 28,
    name: "Agung Gutomo",
    nomorAnggota: "028/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 29,
    name: "John Rinaldi",
    nomorAnggota: "029/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 30,
    name: "Khairiah",
    nomorAnggota: "030/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 31,
    name: "Andriani",
    nomorAnggota: "031/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 32,
    name: "Ulfinora",
    nomorAnggota: "032/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 33,
    name: "Ernawati",
    nomorAnggota: "033/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 34,
    name: "Budi Haryono",
    nomorAnggota: "034/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 35,
    name: "Agusri",
    nomorAnggota: "035/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 36,
    name: "Miswan",
    nomorAnggota: "036/KPA EMC²/1991",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 37,
    name: "Yudison",
    nomorAnggota: "037/KPA EMC²/1992",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 38,
    name: "Rudi Zulkarnaen",
    nomorAnggota: "038/KPA EMC²/1992",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 39,
    name: "Herry Haryono",
    nomorAnggota: "039/KPA EMC²/1992",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 40,
    name: "Hapri",
    nomorAnggota: "040/KPA EMC²/1992",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 41,
    name: "Irfan Sinungan",
    nomorAnggota: "041/KPA EMC²/1993",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 42,
    name: "Rayan Murfhy",
    nomorAnggota: "042/KPA EMC²/1993",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 43,
    name: "Prabowo",
    nomorAnggota: "043/KPA EMC²/1993",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 44,
    name: "Darwin S",
    nomorAnggota: "044/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 45,
    name: "Teddy Hardyansyah",
    nomorAnggota: "045/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 46,
    name: "Hernawan",
    nomorAnggota: "046/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 47,
    name: "Rudi Hidayat",
    nomorAnggota: "047/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 48,
    name: "Bahrul Paham",
    nomorAnggota: "048/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 49,
    name: "Raflis",
    nomorAnggota: "049/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 50,
    name: "Hendra Mardion",
    nomorAnggota: "050/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 51,
    name: "Caroline Kalempouw",
    nomorAnggota: "051/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 52,
    name: "Siti Hajar",
    nomorAnggota: "052/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 53,
    name: "Maria Erna",
    nomorAnggota: "053/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 54,
    name: "Saiful Isnandar",
    nomorAnggota: "054/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 55,
    name: "Azmanto",
    nomorAnggota: "055/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 56,
    name: "Dodi Chandra",
    nomorAnggota: "056/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 57,
    name: "Adria Nellis",
    nomorAnggota: "057/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 58,
    name: "Kokok Yulianto",
    nomorAnggota: "058/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 59,
    name: "Kuncoro Hadi S",
    nomorAnggota: "059/KPA EMC²/1995",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 60,
    name: "Desi Sagita",
    nomorAnggota: "060/KPA EMC²/1996",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 61,
    name: "Yusmanita",
    nomorAnggota: "061/KPA EMC²/1996",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 62,
    name: "Jafril",
    nomorAnggota: "062/KPA EMC²/1996",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 63,
    name: "Gustina Triandini",
    nomorAnggota: "063/KPA EMC²/1996",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 64,
    name: "Ulvah Rahmi",
    nomorAnggota: "064/KPA EMC²/1996",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 65,
    name: "Siti Aminah",
    nomorAnggota: "065/KPA EMC²/1996",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 66,
    name: "Novel Iskandar",
    nomorAnggota: "066/KPA EMC²/1997",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 67,
    name: "Sri Mundarsih",
    nomorAnggota: "067/KPA EMC²/1997",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 68,
    name: "Yandri Dinata",
    nomorAnggota: "068/KPA EMC²/1997",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 69,
    name: "Donna Rita",
    nomorAnggota: "069/KPA EMC²/1997",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 70,
    name: "Edi Saputra",
    nomorAnggota: "070/KPA EMC²/1997",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 71,
    name: "Andi Kusman",
    nomorAnggota: "071/KPA EMC²/1997",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 72,
    name: "Adek Irawan",
    nomorAnggota: "072/KPA EMC²/1997",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 73,
    name: "Donny Kasri",
    nomorAnggota: "073/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 74,
    name: "Nurasiah Ngendrek",
    nomorAnggota: "074/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 75,
    name: "Rami Yanta",
    nomorAnggota: "075/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 76,
    name: "Yussi Wendi",
    nomorAnggota: "076/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 77,
    name: "Zikra Atika Yenni",
    nomorAnggota: "077/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 78,
    name: "Nofi Rustam",
    nomorAnggota: "078/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 79,
    name: "Jefri Hidayat",
    nomorAnggota: "079/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 80,
    name: "Juniati Muliani",
    nomorAnggota: "080/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 81,
    name: "Lidia Permata Sari",
    nomorAnggota: "081/KPA EMC²/1998",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 82,
    name: "Firman",
    nomorAnggota: "082/KPA EMC²/1999",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 83,
    name: "Hamka B.H",
    nomorAnggota: "083/KPA EMC²/1999",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 84,
    name: "Kardi",
    nomorAnggota: "084/KPA EMC²/1999",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 85,
    name: "Dede Kunaifi",
    nomorAnggota: "085/KPA EMC²/2000",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 86,
    name: "Widya Astuti",
    nomorAnggota: "086/KPA EMC²/2000",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 87,
    name: "Novi Hendri",
    nomorAnggota: "087/KPA EMC²/2000",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 88,
    name: "Desi Setiawati",
    nomorAnggota: "088/KPA EMC²/2000",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 89,
    name: "Maiyusrizal",
    nomorAnggota: "089/KPA EMC²/2000",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 90,
    name: "Roza Emilda",
    nomorAnggota: "090/KPA EMC²/2001",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 91,
    name: "Risnetim",
    nomorAnggota: "091/KPA EMC²/2001",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 92,
    name: "Lina Oktaviani",
    nomorAnggota: "092/KPA EMC²/2001",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 93,
    name: "Firdaus",
    nomorAnggota: "093/KPA EMC²/2001",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 94,
    name: "Norazah Aziz",
    nomorAnggota: "094/KPA EMC²/2001",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 95,
    name: "Melvina Sirait",
    nomorAnggota: "095/KPA EMC²/2001",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 96,
    name: "Sri Rahma Yanti",
    nomorAnggota: "096/KPA EMC²/2002",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 97,
    name: "Elna Johani",
    nomorAnggota: "097/KPA EMC²/2002",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 98,
    name: "Syaidina Umar",
    nomorAnggota: "098/KPA EMC²/2002",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 99,
    name: "Yeni Gusmeri",
    nomorAnggota: "099/KPA EMC²/2002",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 100,
    name: "Fitria Gustia Dewi",
    nomorAnggota: "100/KPA EMC²/2002",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 101,
    name: "Ali Afriandi",
    nomorAnggota: "101/KPA EMC²/2002",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 102,
    name: "Porri Nofrizal",
    nomorAnggota: "102/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 103,
    name: "Firman Arfan",
    nomorAnggota: "103/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 104,
    name: "Desi Mulyanti",
    nomorAnggota: "104/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 105,
    name: "Supeni",
    nomorAnggota: "105/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 106,
    name: "Mayasari",
    nomorAnggota: "106/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 107,
    name: "Wahyuni",
    nomorAnggota: "107/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 108,
    name: "Yeprizal",
    nomorAnggota: "108/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 109,
    name: "Adi Prianta",
    nomorAnggota: "109/KPA EMC²/2004",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 110,
    name: "Marni Suryanti",
    nomorAnggota: "110/KPA EMC²/2005",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 111,
    name: "Rina Risanti",
    nomorAnggota: "111/KPA EMC²/2005",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 112,
    name: "Istiqomah Marfu'ah",
    nomorAnggota: "112/KPA EMC²/2006",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 113,
    name: "Fitri Yani",
    nomorAnggota: "113/KPA EMC²/2006",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 114,
    name: "Andre Fristian",
    nomorAnggota: "114/KPA EMC²/2006",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 115,
    name: "Elsy Sanika",
    nomorAnggota: "115/KPA EMC²/2006",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 116,
    name: "Imam Rosidin",
    nomorAnggota: "116/KPA EMC²/2006",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 117,
    name: "Yovi Wydiastuti",
    nomorAnggota: "117/KPA EMC²/2006",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 118,
    name: "Saidul Rahman",
    nomorAnggota: "118/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 119,
    name: "Pipit Susanti",
    nomorAnggota: "119/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 120,
    name: "Riko Kurniawan",
    nomorAnggota: "120/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 121,
    name: "Wira Suhendra",
    nomorAnggota: "121/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 122,
    name: "Nuryuliani",
    nomorAnggota: "122/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 123,
    name: "Cornelius Sanjaya",
    nomorAnggota: "123/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 124,
    name: "Ridho Purnama Putra",
    nomorAnggota: "124/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 125,
    name: "Dwi Laaswati",
    nomorAnggota: "125/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 126,
    name: "Erliana",
    nomorAnggota: "126/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 127,
    name: "Kartini",
    nomorAnggota: "127/KPA EMC²/2007",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 128,
    name: "Okmi Zerlan",
    nomorAnggota: "128/KPA EMC²/2008",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 129,
    name: "Kori Korneliawati",
    nomorAnggota: "129/KPA EMC²/2008",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 130,
    name: "Hariyani",
    nomorAnggota: "130/KPA EMC²/2008",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 131,
    name: "Dewi Susanti",
    nomorAnggota: "131/KPA EMC²/2008",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 132,
    name: "Liza Siswita",
    nomorAnggota: "132/KPA EMC²/2009",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 133,
    name: "Riski Febriani",
    nomorAnggota: "133/KPA EMC²/2009",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 134,
    name: "Donny Hariza",
    nomorAnggota: "134/KPA EMC²/2010",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 135,
    name: "Devitri Wulansari",
    nomorAnggota: "135/KPA EMC²/2010",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 136,
    name: "Saziati Fauzi",
    nomorAnggota: "136/KPA EMC²/2010",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 137,
    name: "Hikmatullah",
    nomorAnggota: "137/KPA EMC²/2010",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 138,
    name: "Margaretta Tiolina Siregar",
    nomorAnggota: "138/KPA EMC²/2010",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 139,
    name: "Fera Yunitanti",
    nomorAnggota: "139/KPA EMC²/2010",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 140,
    name: "Hadi Hidayat",
    nomorAnggota: "140/KPA EMC²/2012",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 141,
    name: "Doni Susanto",
    nomorAnggota: "141/KPA EMC²/2012",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 142,
    name: "Ahmad Fitriansyah",
    nomorAnggota: "142/KPA EMC²/2012",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 143,
    name: "Dori Zafrizal",
    nomorAnggota: "143/KPA EMC²/2013",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 144,
    name: "Arian Trianov S",
    nomorAnggota: "144/KPA EMC²/2013",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 145,
    name: "Ray Afriando",
    nomorAnggota: "145/KPA EMC²/2013",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 146,
    name: "Agus Prastama",
    nomorAnggota: "146/KPA EMC²/2013",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 147,
    name: "Rita Fitriyani",
    nomorAnggota: "147/KPA EMC²/2013",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 148,
    name: "Wildan Adli",
    nomorAnggota: "148/KPA EMC²/2013",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 149,
    name: "Milawinda",
    nomorAnggota: "149/KPA EMC²/2013",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 150,
    name: "Mimwindayani",
    nomorAnggota: "150/KPA EMC²/2014",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 151,
    name: "Sigit Priya Utama",
    nomorAnggota: "151/KPA EMC²/2014",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 152,
    name: "Winarto",
    nomorAnggota: "152/KPA EMC²/2014",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 153,
    name: "Sumarni",
    nomorAnggota: "153/KPA EMC²/2014",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 154,
    name: "An Hafni",
    nomorAnggota: "154/KPA EMC²/2014",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 155,
    name: "Yunita Fatma Azis",
    nomorAnggota: "155/KPA EMC²/2014",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 156,
    name: "Lora Angraini",
    nomorAnggota: "156/KPA EMC²/2016",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 157,
    name: "Rio Febrianto",
    nomorAnggota: "157/KPA EMC²/2018",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 158,
    name: "Rina Noviana",
    nomorAnggota: "158/KPA EMC²/2019",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 159,
    name: "Seliana Putri",
    nomorAnggota: "159/KPA EMC²/2019",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 160,
    name: "Nur Aisyah Arifin",
    nomorAnggota: "160/KPA EMC²/2019",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 161,
    name: "Siska Afriani",
    nomorAnggota: "161/KPA EMC²/2019",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 162,
    name: "Muhammad Ahlunnazah",
    nomorAnggota: "162/KPA EMC²/2019",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 163,
    name: "Ilham Yurestira",
    nomorAnggota: "163/KPA EMC²/2019",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 164,
    name: "Risna Ramadania",
    nomorAnggota: "164/KPA EMC²/2021",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 165,
    name: "Siti Ma'rifa",
    nomorAnggota: "165/KPA EMC²/2021",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 166,
    name: "Sri Ningsih Sitorus",
    nomorAnggota: "166/KPA EMC²/2021",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 167,
    name: "Siti Aisyah Sinurat",
    nomorAnggota: "167/KPA EMC²/2021",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 168,
    name: "Muhammad Farhan",
    nomorAnggota: "168/KPA EMC²/2022",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 169,
    name: "Dian Opa",
    nomorAnggota: "169/KPA EMC²/2022",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 170,
    name: "Syafiqah Amirah Defani",
    nomorAnggota: "170/KPA EMC²/2022",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 171,
    name: "Hurul 'Aini",
    nomorAnggota: "171/KPA EMC²/2022",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 172,
    name: "Hawa Mardika Agustin",
    nomorAnggota: "172/KPA EMC²/2022",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 173,
    name: "Desti Seri Fatimah",
    nomorAnggota: "173/KPA EMC²/2022",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 174,
    name: "Ali Musthafa Kamal",
    nomorAnggota: "174/KPA EMC²/2022",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 175,
    name: "Elma",
    nomorAnggota: "175/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 176,
    name: "Erni Fibrianti",
    nomorAnggota: "176/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 177,
    name: "Suci Rahmawati",
    nomorAnggota: "177/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 178,
    name: "Sarah Nurhaliza",
    nomorAnggota: "178/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 179,
    name: "Riska Syintiandari",
    nomorAnggota: "179/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 180,
    name: "Resti Julian Amanda",
    nomorAnggota: "180/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 181,
    name: "Syahren Nabila",
    nomorAnggota: "181/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 182,
    name: "Tiara Yunisa",
    nomorAnggota: "182/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 183,
    name: "Alzena Davita",
    nomorAnggota: "183/KPA EMC²/2023",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 184,
    name: "Qodri Illahi",
    nomorAnggota: "184/KPA EMC²/2025",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 185,
    name: "Nur Afni Rahmadani",
    nomorAnggota: "185/KPA EMC²/2025",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 186,
    name: "M. Rizky Al Habibi Lubis",
    nomorAnggota: "186/KPA EMC²/2025",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 187,
    name: "Gressita Sihotang",
    nomorAnggota: "187/KPA EMC²/2025",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
  {
    id: 188,
    name: "Feronika",
    nomorAnggota: "188/KPA EMC²/2025",
    jurusan: "",
    nomorTelepon: "",
    status: "Aktif",
    avatarUrl: "",
  },
];
